### ISSUE TITLE
Changing the template of an instance with volumes attached in terraform fails

### ISSUE THREAD

**Issue by franzpgarcia** [cloud-ca/terraform-provider-cloudca#16]
It calls the update on the volumes and tries to detach the volume but the instance has been destroyed.
ex:
cloudca_volume.data_volume_43_2: Modifying...
  instance_id: "c6cfd6a4-ee15-4d86-b17d-7dade9c95ff1" => "de0518ef-81c6-427e-958f-64aa3170495a"
cloudca_volume.data_volume_43_4: Modifying...
  instance_id: "c6cfd6a4-ee15-4d86-b17d-7dade9c95ff1" => "de0518ef-81c6-427e-958f-64aa3170495a"
cloudca_volume.data_volume_43_3: Modifying...
  instance_id: "c6cfd6a4-ee15-4d86-b17d-7dade9c95ff1" => "de0518ef-81c6-427e-958f-64aa3170495a"
cloudca_volume.data_volume_43: Modifying...
  instance_id: "c6cfd6a4-ee15-4d86-b17d-7dade9c95ff1" => "de0518ef-81c6-427e-958f-64aa3170495a"

* cloudca_volume.data_volume_44: [ERROR] Received HTTP status code 400
[ERROR] Error Code: 2704, Message: This volume is not attached to existing instance, Context: {}

* cloudca_volume.data_volume_42: [ERROR] Received HTTP status code 400
[ERROR] Error Code: 2704, Message: This volume is not attached to existing instance, Context: {}

* cloudca_volume.data_volume_43_4: [ERROR] Received HTTP status code 400
[ERROR] Error Code: 2704, Message: This volume is not attached to existing instance, Context: {}

* cloudca_volume.data_volume_43: [ERROR] Received HTTP status code 400
[ERROR] Error Code: 2704, Message: This volume is not attached to existing instance, Context: {}

* cloudca_volume.data_volume_43_3: [ERROR] Received HTTP status code 400
[ERROR] Error Code: 2704, Message: This volume is not attached to existing instance, Context: {}

* cloudca_volume.data_volume_43_2: [ERROR] Received HTTP status code 400
[ERROR] Error Code: 2704, Message: This volume is not attached to existing instance, Context: {}

**Comment by simongodard** [comment]
@franzpgarcia: is there a way we could detach the volumes before the delete instance and attach them back after the instance is created again?

**Comment by simongodard** [comment]
Sorry I closed the issue by accident...

**Comment by franzpgarcia** [comment]
The issue is that on the destroy instance you don't have access to the state of a volume.
