### ISSUE TITLE
Terraform binary package name doesn't make sense

### ISSUE THREAD

**Issue by franzpgarcia** [cloud-ca/terraform-provider-cloudca#17]
When I download the terraform bin driver for cloud.ca the package name = darwin-amd64.zip on https://github.com/cloud-ca/terraform-provider-cloudca/releases
It would make more sense if the pkg name would look as something like terraform-cloudca_0.5.0_darwin.zip.
It would also make sense if we would provide md5sum of those files.

**Comment by simongodard** [comment]
Fixed by PR #29
