### ISSUE TITLE
If you don't specify a network id and instance ids, the load balancer rule fails to create because of a concurrency issue

### ISSUE THREAD

**Issue by franzpgarcia** [cloud-ca/terraform-provider-cloudca#26]
Since there's no dependency between a lbr and a load balancing tier, it tries to create the lbr first and fails to create because it can't find the tier.

I think the network id should be required.

**Comment by prollynomial** [comment]
Like we talked about before the demo, wouldn't a requirement on non-empty `instanceId`s also fix this? Makes a lot of sense to force instances in an LBR in a terraform user context.

```
LBR -(depends)->
  public IP,
  instance -(depends)->
    tier (in this context, an LB-enabled tier)
```

**Comment by franzpgarcia** [comment]
My instanceIds wasn't null though it was []. I think it's better to have the networkId required because your terraform graph would be clearer.

**Comment by prollynomial** [comment]
Regardless of null or empty list, I'm not sure that that's a valid use-case for a terraform user.

**Comment by franzpgarcia** [comment]
How do you enforce the instanceIds to be non-null. Having logic in the create won't work because your terraform plan will pass. At least with a required networkId, terraform plan will tell you need to specify lbr -> tier relation.
